add getLatestSubcase Function and change title
kanselarij-vlaanderen/vlaams-parlement-sync-service pull request #13
Opened 2024-02-19 10:28 UTC by SchrodingersCat00

2024-02-19 14:21 UTC, sergiofenoll requested changes

2024-02-19 14:21 UTC, sergiofenoll commented on lib/decisionmaking-flow.js
> +    SELECT ?uri ?title {
Add `DISTINCT` here (it's just good practice to have it, even if you're only selecting 1 row.

2024-02-19 14:21 UTC, sergiofenoll commented on lib/decisionmaking-flow.js
> +    } ORDER BY ?created LIMIT 1
```suggestion
    } ORDER BY DESC(?created) LIMIT 1
```

2024-02-21 12:49 UTC, tdn approved these changes

2024-02-21 12:57 UTC, merged